services:
  - type: web
    name: offhand-wow
    env: static
    buildCommand: ""
    staticPublishPath: ./Website
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
